[package]
name = "pkgs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = "0.9.5"

[dev-dependencies]
googletest = "0.14.2"
indoc = "2.0.6"
tempfile = "3.21.0"
